In [4]:
y=pd.Period('2016')
y

Period('2016', 'Y-DEC')

In [5]:
y.start_time

Timestamp('2016-01-01 00:00:00')

In [7]:
m=pd.Period('2011-1',freq='M')
m

Period('2011-01', 'M')

In [8]:
m.start_time

Timestamp('2011-01-01 00:00:00')

In [9]:
m.end_time

Timestamp('2011-01-31 23:59:59.999999999')

In [10]:
m+1

Period('2011-02', 'M')

In [13]:
d=pd.Period('2016-02-28')
d

Period('2016-02-28', 'D')

In [14]:
d+1 # Includes leap year

Period('2016-02-29', 'D')

### h+pd.offsets.Hour(1)
h is freq ='H'

In [19]:
q=pd.Period('2017Q1')
q

Period('2017Q1', 'Q-DEC')

In [20]:
q+1

Period('2017Q2', 'Q-DEC')

In [23]:
q.asfreq('h',how='start')

Period('2017-01-01 00:00', 'h')

In [24]:
q1=pd.Period('2017Q1',freq='Q-JAN')
q1

Period('2017Q1', 'Q-JAN')

In [25]:
q2=pd.Period('2018Q1',freq='Q-JAN')
q2

Period('2018Q1', 'Q-JAN')

In [26]:
q2-q1

In [28]:
idx = pd.period_range('2011','2017',freq='Q-JAN')
# idx = pd.period_range('2011',periods=10,freq='Q-JAN')
idx

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3',
             '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1',
             '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
             '2017Q4'],
            dtype='period[Q-JAN]')

In [29]:
idx[0]

Period('2011Q4', 'Q-JAN')

In [30]:
idx[0].end_time

Timestamp('2011-01-31 23:59:59.999999999')

In [34]:
ps=pd.Series(np.random.randn(len(idx)),idx)
ps

2011Q4   -1.010039
2012Q1   -0.220605
2012Q2   -0.903151
2012Q3   -0.311987
2012Q4    0.854916
2013Q1   -1.071366
2013Q2   -1.393482
2013Q3   -0.546273
2013Q4   -0.043928
2014Q1   -0.509116
2014Q2   -1.042917
2014Q3    0.440755
2014Q4   -0.144559
2015Q1   -1.054819
2015Q2   -1.329620
2015Q3    0.134149
2015Q4    0.330215
2016Q1    0.259192
2016Q2    0.348157
2016Q3    1.064614
2016Q4   -1.619202
2017Q1    1.509058
2017Q2    0.127761
2017Q3   -1.744098
2017Q4   -0.327876
Freq: Q-JAN, dtype: float64

In [36]:
ps['2011']

2011Q4   -1.010039
2012Q1   -0.220605
2012Q2   -0.903151
2012Q3   -0.311987
2012Q4    0.854916
Freq: Q-JAN, dtype: float64

In [37]:
pst=ps.to_timestamp()
pst

2010-11-01   -1.010039
2011-02-01   -0.220605
2011-05-01   -0.903151
2011-08-01   -0.311987
2011-11-01    0.854916
2012-02-01   -1.071366
2012-05-01   -1.393482
2012-08-01   -0.546273
2012-11-01   -0.043928
2013-02-01   -0.509116
2013-05-01   -1.042917
2013-08-01    0.440755
2013-11-01   -0.144559
2014-02-01   -1.054819
2014-05-01   -1.329620
2014-08-01    0.134149
2014-11-01    0.330215
2015-02-01    0.259192
2015-05-01    0.348157
2015-08-01    1.064614
2015-11-01   -1.619202
2016-02-01    1.509058
2016-05-01    0.127761
2016-08-01   -1.744098
2016-11-01   -0.327876
Freq: QS-NOV, dtype: float64

In [42]:
pst.to_period()

2010Q4   -1.010039
2011Q1   -0.220605
2011Q2   -0.903151
2011Q3   -0.311987
2011Q4    0.854916
2012Q1   -1.071366
2012Q2   -1.393482
2012Q3   -0.546273
2012Q4   -0.043928
2013Q1   -0.509116
2013Q2   -1.042917
2013Q3    0.440755
2013Q4   -0.144559
2014Q1   -1.054819
2014Q2   -1.329620
2014Q3    0.134149
2014Q4    0.330215
2015Q1    0.259192
2015Q2    0.348157
2015Q3    1.064614
2015Q4   -1.619202
2016Q1    1.509058
2016Q2    0.127761
2016Q3   -1.744098
2016Q4   -0.327876
Freq: Q-DEC, dtype: float64

In [44]:
df=pd.read_csv('wmt.csv')
df

  Line Item  2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
0   Revenue  115904  120854  118179  130936  117542
1  Expenses   86544   89485   87484   97743   87688
2    Profit   29360   31369   30695   33193   29854

In [45]:
df.set_index('Line Item',inplace=True)
df

           2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
Line Item
Revenue    115904  120854  118179  130936  117542
Expenses    86544   89485   87484   97743   87688
Profit      29360   31369   30695   33193   29854

In [46]:
df=df.T
df

Line Item  Revenue  Expenses  Profit
2017Q1      115904     86544   29360
2017Q2      120854     89485   31369
2017Q3      118179     87484   30695
2017Q4      130936     97743   33193
2018Q1      117542     87688   29854

In [47]:
df.index

Index(['2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1'], dtype='object')

In [48]:
df.index=pd.PeriodIndex(df.index,freq='Q-JAN')
df.index

PeriodIndex(['2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1'], dtype='period[Q-JAN]')

In [50]:
df['start_date']=df.index.map(lambda x: x.start_time)

In [51]:
df['end_date']=df.index.map(lambda x: x.end_time)

In [52]:
df

Line Item  Revenue  Expenses  Profit start_date                      end_date
2017Q1      115904     86544   29360 2016-02-01 2016-04-30 23:59:59.999999999
2017Q2      120854     89485   31369 2016-05-01 2016-07-31 23:59:59.999999999
2017Q3      118179     87484   30695 2016-08-01 2016-10-31 23:59:59.999999999
2017Q4      130936     97743   33193 2016-11-01 2017-01-31 23:59:59.999999999
2018Q1      117542     87688   29854 2017-02-01 2017-04-30 23:59:59.999999999